inputs:
  version:
    default: 1.0.0
    required: false
jobs:
  steps:
    - name: Build nuget packages
      run: dotnet pack --configuration Release --include-source --include-symbols --nologo --no-restore --output .artifacts/packages --verbosity normal -p:PackageVersion=$input.version *.sln