name: Build workflow
defaults:
  run:
    shell: bash
    working-directory: examples/dotnet
on:
  pull_request:
    branches: [ main ]
    paths: [ "examples/dotnet/**" ]
  push:
    branches: [ main ]
    paths: [ "examples/dotnet/**" ]
  workflow_dispatch:
jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
  build:
    env:
      sonar_project_key: examples-dotnet
    name: Build
    needs: checkout
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/artifacts-build-version/action.yml
      - uses: ./.github/actions/dotnet-build/action.yml
        with:
          version: $env.artifacts_version_preview
      - uses: ./.github/actions/publish-code-coverage/action.yml
        with:
          version: $env.artifacts_version_preview
      - uses: ./.github/actions/nuget-build/action.yml
        with:
          version: $env.artifacts_version_preview
      - uses: ./.github/actions/nuget-publish/action.yml
        with:
          version: $env.artifacts_version_preview