name: Release .NET solution (example)
defaults:
  run:
    shell: bash
    working-directory: examples/dotnet
on:
  workflow_dispatch:
jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
  build:
    env:
      sonar_project_key: examples-dotnet
    name: Build
    needs: checkout
    runs-on: self-hosted
    steps:
      - uses: josemaria-toro/github/.github/actions/artifacts-build-version@main
      - uses: josemaria-toro/github/.github/actions/dotnet-build@main
        with:
          version: $env.artifacts_version
      - uses: josemaria-toro/github/.github/actions/publish-code-coverage@main
        with:
          version: $env.artifacts_version
      - uses: josemaria-toro/github/.github/actions/nuget-build@main
        with:
          version: $env.artifacts_version
      - uses: josemaria-toro/github/.github/actions/nuget-publish@main
        with:
          version: $env.artifacts_version