name: Build .NET solution (example)
defaults:
  run:
    shell: bash
    working-directory: examples/dotnet
on:
  pull_request:
    branches: [ main ]
    paths: [ "examples/dotnet/**" ]
  push:
    branches: [ main ]
    paths: [ "examples/dotnet/**" ]
  workflow_dispatch:
jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
  build:
    env:
      sonar_project_key: examples-dotnet
    name: Build
    needs: checkout
    runs-on: self-hosted
    steps:
      - uses: josemaria-toro/github/workflows/artifacts-build-version.yml@main
      - uses: josemaria-toro/github/workflows/dotnet-build.yml@main
        with:
          version: $env.artifacts_version_preview
      - uses: josemaria-toro/github/workflows/publish-code-coverage.yml@main
        with:
          version: $env.artifacts_version_preview
      - uses: josemaria-toro/github/workflows/nuget-build.yml@main
        with:
          version: $env.artifacts_version_preview
      - uses: josemaria-toro/github/workflows/nuget-publish.yml@main
        with:
          version: $env.artifacts_version_preview